// frontend/src/lib/components/feed/ItemCard.svelte
<script>
    import { MEDIA_BASE_URL } from '../../api/items.js';

    export let item;

    // Format a datetime string to a readable short date
    function formatDate(dateStr) {
        if (!dateStr) return '';
        return new Date(dateStr).toLocaleDateString(undefined, {
            year: 'numeric',
            month: 'short',
            day: 'numeric',
        });
    }

    $: thumbnailSrc = item.thumbnail_path ? `${MEDIA_BASE_URL}/media/${item.thumbnail_path}` : null;
</script>

<article class="item-card" class:unread={!item.is_read} class:nsfw={item.is_nsfw}>
    <button class="card-btn" on:click>
        <!-- Thumbnail -->
        <div class="card-thumbnail">
            {#if thumbnailSrc}
                <img src={thumbnailSrc} alt={item.title} />
            {:else}
                <div class="thumbnail-placeholder">
                    <span>{item.title.charAt(0).toUpperCase()}</span>
                </div>
            {/if}

            <!-- Badges overlay -->
            <div class="card-badges">
                {#if item.is_nsfw}
                    <span class="badge nsfw">NSFW</span>
                {/if}
                {#if !item.is_public}
                    <span class="badge unlisted">unlisted</span>
                {/if}
                {#if item.is_favorite}
                    <span class="badge favorite">♥</span>
                {/if}
            </div>
        </div>

        <!-- Content -->
        <div class="card-content">
            <h3 class="card-title">{item.title}</h3>

            {#if item.summary || item.description}
                <p class="card-summary">{item.summary || item.description}</p>
            {/if}

            <div class="card-meta">
                {#if item.author}
                    <span class="card-author">{item.author.name}</span>
                {/if}
                <span class="card-date">{formatDate(item.source_updated_at)}</span>
            </div>

            {#if item.tags?.length > 0}
                <div class="card-tags">
                    {#each item.tags.slice(0, 3) as tag}
                        <span class="tag">{tag}</span>
                    {/each}
                </div>
            {/if}
        </div>
    </button>
</article>

<style>
    .item-card {
        background: var(--bg-secondary);
        border: 1px solid var(--border);
        border-radius: var(--radius);
        overflow: hidden;
        cursor: pointer;
        transition:
            box-shadow var(--transition),
            transform var(--transition);
        display: flex;
        flex-direction: column;
    }

    .item-card:hover {
        box-shadow: var(--shadow);
        transform: translateY(-2px);
    }

    .item-card.unread {
        border-left: 3px solid var(--accent);
    }

    /* Dim read items slightly */
    .item-card:not(.unread) {
        opacity: 0.7;
    }

    .item-card:not(.unread):hover {
        opacity: 1;
    }

    .card-btn {
        display: flex;
        flex-direction: column;
        width: 100%;
        text-align: left;
    }

    /* Thumbnail */
    .card-thumbnail {
        position: relative;
        width: 100%;
        aspect-ratio: 16 / 9;
        background: var(--bg-tertiary);
        overflow: hidden;
        flex-shrink: 0;
    }

    .card-thumbnail img {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }

    .thumbnail-placeholder {
        width: 100%;
        height: 100%;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 2rem;
        font-weight: 700;
        color: var(--text-muted);
    }

    /* Badges */
    .card-badges {
        position: absolute;
        top: 0.4rem;
        left: 0.4rem;
        display: flex;
        flex-direction: column;
        gap: 0.25rem;
    }

    .badge {
        font-size: 0.65rem;
        font-weight: 700;
        padding: 0.15rem 0.35rem;
        border-radius: 4px;
        text-transform: uppercase;
        letter-spacing: 0.04em;
    }

    .badge.nsfw {
        background: var(--danger);
        color: white;
    }

    .badge.unlisted {
        background: var(--text-muted);
        color: white;
    }

    .badge.favorite {
        background: #e8b84b;
        color: white;
    }

    /* Content */
    .card-content {
        padding: 0.6rem 0.75rem 0.75rem;
        display: flex;
        flex-direction: column;
        gap: 0.35rem;
        flex: 1;
    }

    .card-title {
        font-size: 0.875rem;
        font-weight: 600;
        line-height: 1.3;
        display: -webkit-box;
        -webkit-line-clamp: 2;
        line-clamp: 2;
        -webkit-box-orient: vertical;
        overflow: hidden;
        color: var(--text-primary);
    }

    .card-summary {
        font-size: 0.775rem;
        color: var(--text-secondary);
        line-height: 1.4;
        display: -webkit-box;
        -webkit-line-clamp: 3;
        line-clamp: 3;
        -webkit-box-orient: vertical;
        overflow: hidden;
    }

    .card-meta {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 0.5rem;
        margin-top: auto;
    }

    .card-author {
        font-size: 0.75rem;
        color: var(--text-muted);
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        max-width: 100px;
    }

    .card-date {
        font-size: 0.75rem;
        color: var(--text-muted);
        white-space: nowrap;
        flex-shrink: 0;
    }

    .card-tags {
        display: flex;
        flex-wrap: wrap;
        gap: 0.25rem;
    }

    .tag {
        font-size: 0.65rem;
        padding: 0.1rem 0.35rem;
        border-radius: 4px;
        background: var(--bg-tertiary);
        color: var(--text-secondary);
        white-space: nowrap;
    }
</style>

// frontend/src/components/items/ItemCard.tsx
import { Badge } from '@/components/ui/badge'
import { Card, CardContent } from '@/components/ui/card'
import type { Item } from '@/types'

interface ItemCardProps {
  item: Item
  onClick: () => void
}

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString(undefined, {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  })
}

function truncate(text: string | null, max: number) {
  if (!text) return null
  return text.length > max ? text.slice(0, max) + '…' : text
}

export function ItemCard({ item, onClick }: ItemCardProps) {
  const preview = truncate(item.summary ?? item.description, 100)

  return (
    <Card
      onClick={onClick}
      className={`cursor-pointer transition-opacity hover:opacity-90 ${!item.is_read ? '' : 'opacity-50'}`}
    >
      {/* thumbnail */}
      {item.thumbnail_path && (
        <div className="aspect-[3/2] w-full overflow-hidden rounded-t-lg bg-muted">
          <img
            src={`http://localhost:8000/media/${item.thumbnail_path}`}
            alt={item.title}
            className="h-full w-full object-cover"
            onError={e => { (e.target as HTMLImageElement).style.display = 'none' }}
          />
        </div>
      )}

      <CardContent className="flex flex-col gap-2 p-3">
        {/* badges */}
        <div className="flex flex-wrap gap-1">
          {item.is_favorite && (
            <Badge variant="secondary" className="text-yellow-500">★ Favorite</Badge>
          )}
          {item.is_nsfw && (
            <Badge variant="destructive">NSFW</Badge>
          )}
          {!item.is_public && (
            <Badge variant="outline">Private</Badge>
          )}
        </div>

        {/* title */}
        <p className="text-sm font-semibold leading-tight line-clamp-2">{item.title}</p>

        {/* preview text */}
        {preview && (
          <p className="text-xs text-muted-foreground line-clamp-3">{preview}</p>
        )}

        {/* tags */}
        {item.tags.length > 0 && (
          <div className="flex flex-wrap gap-1">
            {item.tags.slice(0, 3).map(tag => (
              <Badge key={tag} variant="outline" className="text-xs">{tag}</Badge>
            ))}
            {item.tags.length > 3 && (
              <Badge variant="outline" className="text-xs">+{item.tags.length - 3}</Badge>
            )}
          </div>
        )}

        {/* date + author */}
        <div className="flex items-center justify-between text-xs text-muted-foreground">
          <span>{formatDate(item.source_updated_at)}</span>
        </div>
      </CardContent>
    </Card>
  )
}
