// frontend/src/lib/components/feed/ItemGrid.svelte
<script>
    import { itemsApi } from '../../api/items.js';
    import { selectedFeedId } from '../../stores/navigation.js';
    import ItemModal from '../item/ItemModal.svelte';
    import ItemCard from './ItemCard.svelte';

    let items = [];
    let loading = true;
    let error = null;

    let selectedItem = null;

    // Reload items whenever selected feed changes
    $: if ($selectedFeedId) loadItems($selectedFeedId);

    async function loadItems(feedId) {
        loading = true;
        error = null;
        items = [];
        try {
            items = await itemsApi.list(feedId);
        } catch (e) {
            error = e.message;
        } finally {
            loading = false;
        }
    }

    function openItem(item) {
        selectedItem = item;
    }

    function closeModal() {
        selectedItem = null;
    }

    function handleItemUpdate(updatedItem) {
        items = items.map((i) => (i.id === updatedItem.id ? updatedItem : i));
        selectedItem = updatedItem;
    }
</script>

{#if $selectedFeedId}
    <div class="item-grid-wrapper">
        {#if loading}
            <p class="grid-status">Loading...</p>
        {:else if error}
            <p class="grid-status error">{error}</p>
        {:else if items.length === 0}
            <p class="grid-status">No items yet.</p>
        {:else}
            <div class="item-grid">
                {#each items as item (item.id)}
                    <ItemCard {item} on:click={() => openItem(item)} />
                {/each}
            </div>
        {/if}
        {#if selectedItem}
            <ItemModal item={selectedItem} onClose={closeModal} onUpdate={handleItemUpdate} />
        {/if}
    </div>
{/if}

<style>
    .item-grid-wrapper {
        height: 100%;
        overflow-y: auto;
        padding: 1rem;
    }

    .grid-status {
        color: var(--text-muted);
        font-size: 0.875rem;
        padding: 1rem 0;
    }

    .grid-status.error {
        color: var(--danger);
    }

    .item-grid {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
        gap: 1rem;
    }
</style>

// frontend/src/components/items/ItemGrid.tsx
import { useItems } from '@/hooks/useItems'
import { ItemCard } from '@/components/items/ItemCard'
import { ScrollArea } from '@/components/ui/scroll-area'
import { useState } from 'react'
import { ItemModal } from '@/components/items/ItemModal'
import type { Item } from '@/types'

export function ItemGrid({ feedId }: { feedId: number }) {
  const { data: items, isLoading } = useItems(feedId)
  const [selectedItem, setSelectedItem] = useState<Item | null>(null)

  if (isLoading) return <p className="p-4 text-muted-foreground">Loading items...</p>
  if (!items?.length) return <p className="p-4 text-muted-foreground">No items yet — try scraping.</p>

  return (
    <>
      <ScrollArea className="h-full">
        <div className="grid grid-cols-[repeat(auto-fill,minmax(240px,1fr))] gap-4 p-4">
          {items.map(item => (
            <ItemCard
              key={item.id}
              item={item}
              onClick={() => setSelectedItem(item)}
            />
          ))}
        </div>
      </ScrollArea>

      <ItemModal
        item={selectedItem}
        open={selectedItem !== null}
        onClose={() => setSelectedItem(null)}
      />
    </>
  )
}
